---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/ns.yaml
  - base/netpol.yaml
  - app/repo.yaml
  - app/release.yaml
  - app/rbac.yaml
  - app/pvc.yaml
  - app/secret.yaml
  - app/netpol.yaml
  - backup/secret.yaml
  - backup/rbac.yaml
  - backup/backup.yaml
  - backup/backup-workflowtemplate.yaml
  - backup/restore-workflowtemplate.yaml
