hostname: timtorchen.com
forwardedIP: 192.168.255.200

metallb:
  addressPools:
  - name: public
    protocol: layer2
    addresses: 192.168.255.200/32
  - name: localdns
    protocol: layer2
    addresses: 192.168.255.201/32
  - name: internal
    protocol: layer2
    addresses: 192.168.255.202-192.168.255.210

certmanager:
  wildcardCert:
    name: wildcard-certificate-secret
    dnsNames:
    - "timtorchen.com"
    - "*.timtorchen.com"

nginx:
  defaultCert: system/wildcard-certificate-secret
  public: 
    className: nginx
    exportIP: 192.168.255.200
  personal:
    className: personal
    exportIP: 192.168.255.202

nfsclient:
  nfsServer: 192.168.255.150
  mountPath: /mnt/ssd
  storageClassName: nfs-client

pihole:
  exportIP: 192.168.255.201  
  adlists:
  - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts_without_controversies.txt
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
  - https://v.firebog.net/hosts/static/w3kbl.txt
  - https://adaway.org/hosts.txt
  - https://v.firebog.net/hosts/AdguardDNS.txt
  - https://v.firebog.net/hosts/Admiral.txt
  - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
  - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
  - https://v.firebog.net/hosts/Easylist.txt
  - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
  - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
  - https://v.firebog.net/hosts/Easyprivacy.txt
  - https://v.firebog.net/hosts/Prigent-Ads.txt
  - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
  - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
  - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
  - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
  - https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
  - https://mirror1.malwaredomains.com/files/justdomains
  - https://v.firebog.net/hosts/Prigent-Crypto.txt
  - https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
  - https://www.malwaredomainlist.com/hostslist/hosts.txt
  - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
  - https://phishing.army/download/phishing_army_blocklist_extended.txt
  - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
  - https://v.firebog.net/hosts/Shalla-mal.txt
  - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
  - https://urlhaus.abuse.ch/downloads/hostfile/
  - https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser

  storage: 500Mi
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi

wireguard:
  storage: 100Mi
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 300Mi

openvpn:
  storage: 10Mi
  resources:
    limits:
      cpu: 0.5
      memory: 100Mi
    requests:
      cpu: 0.5
      memory: 100Mi

nextcloud:
  replicaCount: 1
  storage: 100Gi
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi

mariadb:
  storage: 2Gi
  resources:
    limits:
      cpu: 0.5
      memory: 500Mi
    requests:
      cpu: 0.2
      memory: 300Mi

jellyfin:
  # media 
  existingClaimMounts:
  - name: nextcloud
    mountPath: /nextcloud
    existingClaim: nextcloud-nextcloud
  # web static file, config, and database
  storage: 1Gi
  resources:
    limits:
      cpu: 2
      memory: 1Gi
    requests:
      cpu: 1
      memory: 500Mi
  
bitwarden:
  storage: 100Mi
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

prometheus:
  server:
    storage: 8Gi
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 500Mi
  
  altermanager:
    storage: 2Gi
    resources:
      limits:
        cpu: 0.1
        memory: 100Mi
      requests:
        cpu: 0.01
        memory: 30Mi

  pushgateway:
    storage: 2Gi
    resources:
      limits:
        cpu: 0.1
        memory: 100Mi
      requests:
        cpu: 0.01
        memory: 30Mi

grafana:
  storage: 100Mi
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

blog:
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
