---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: rustic-exporter
  name: rustic-exporter
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::262264826613:role/rustic-exporter
    eks.amazonaws.com/audience: sts.amazonaws.com
