---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/ceph.rook.io/cephobjectstore_v1.json
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  namespace: rook-ceph
  name: fast
spec:
  metadataPool:
    failureDomain: host
    deviceClass: nvme
    replicated:
      size: 3
      requireSafeReplicaSize: true
  dataPool:
    failureDomain: host
    deviceClass: nvme
    replicated:
      size: 3
      requireSafeReplicaSize: true
  gateway:
    port: 8080
    instances: 2
