---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/secretstore_v1.json
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  namespace: cloudflared
  name: cloudflared
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: cloudflared
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: cloudflared
  name: cloudflared-secret
spec:
  refreshInterval: "24h"
  secretStoreRef:
    kind: SecretStore
    name: cloudflared
  refreshPolicy: OnChange
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
  ## Get the secret with `cloudflared tunnel token <tunnel-nam> --cred-file credential.json`
  ## The tunnel token fetched on UI is generally the base64 compact version of credential.json
  dataFrom:
    - extract:
        key: /kubernetes/cloudflared
