apiVersion: v1
appVersion: 17.0.0
description: A file sharing server that puts the control and security of your own
  data back into your hands.
home: https://nextcloud.com/
icon: https://cdn.rawgit.com/docker-library/docs/defa5ffc7123177acd60ddef6e16bddf694cc35f/nextcloud/logo.svg
keywords:
- nextcloud
- storage
- http
- web
- php
maintainers:
- email: christian.ingenhaag@googlemail.com
  name: chrisingenhaag
- email: jeff@billimek.com
  name: billimek
name: nextcloud
sources:
- https://github.com/nextcloud/docker
version: 1.12.0
