---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  namespace: kube-system
  name: gateway-api-crd
spec:
  interval: 1m
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.3.0
  ignore: |
    /*
    !/config/crd/standard
    !/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: kube-system
  name: gateway-api-crd
spec:
  prune: false
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: gateway-api-crd
