---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/serviceaccount-v1.json
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: argo-system
  name: argo-workflows-server
  annotations:
    eks.amazonaws.com/audience: sts.amazonaws.com
    eks.amazonaws.com/role-arn: arn:aws:iam::262264826613:role/argo-workflows-server
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/serviceaccount-v1.json
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: argo-system
  name: argo-workflows-controller
