---
name: Helper
on:
  push:
    branches:
      - "action/config"
      - "main"
jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show context
        uses: crazy-max/ghaction-dump-context@v1