---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # crd
  - crd/gateway-api.yaml
  # app
  - app/repo.yaml
  - app/release.yaml
  - app/netpol.yaml
  # bgp
  - bgp/bgpclusterconfig.yaml
  - bgp/bgppeerconfig.yaml
  - bgp/shared-bgpadvertisement.yaml
  # loadbalancer
  - loadbalancer/certificate.yaml
  - loadbalancer/gatewayclass.yaml
  - loadbalancer/gateway.yaml
  - loadbalancer/shared-pool.yaml
